### ISSUE TITLE
ee_Initalize() Error: Error in py_call_impl(callable, dots$args, dots$keywords) : TimeoutError: [WinError 10060]

### ISSUE THREAD

**Issue by TianyaImpression** [r-spatial/rgee#73]
* rgee version: 0.6.2
* R version: 3.6.3
* Operating System: win10
![image](https://user-images.githubusercontent.com/22004043/86874294-b183d300-c112-11ea-843c-95b2a6cda272.png)
I installed rgee 
but I can't run ee_Intiialize（） without Error
Could anyone help me ?

**Comment by giswqs** [comment]
You might not have set up VPN properly. See [here](https://groups.google.com/g/google-earth-engine-developers/c/GeO3d6Utyto).

**Comment by xiaoxiaokuishu** [comment]
> * rgee version: 0.6.2
> * R version: 3.6.3
> * Operating System: win10
>   ![image](https://user-images.githubusercontent.com/22004043/86874294-b183d300-c112-11ea-843c-95b2a6cda272.png)
>   I installed rgee
>   but I can't run ee_Intiialize（） without Error
>   Could anyone help me ?

I also encountered this issue, have you solved it or not?

**Comment by csaybar** [comment]
Hi @xiaoxiaokuishu, unfortunately, this problem was not solved yet.

**Comment by Bhavani88** [comment]
> > * rgee version: 0.6.2
> > * R version: 3.6.3
> > * Operating System: win10
> >   ![image](https://user-images.githubusercontent.com/22004043/86874294-b183d300-c112-11ea-843c-95b2a6cda272.png)
> >   I installed rgee
> >   but I can't run ee_Intiialize（） without Error
> >   Could anyone help me ?
> 
> I also encountered this issue, have you solved it or not?

**Comment by Bhavani88** [comment]
I am encountered with this same issue, have you solved it or not?

**Comment by Mew-YL** [comment]
I got the same issue, have you solved it?

**Comment by taitlw** [comment]
Has there been any development on this problem? I am having the same issue. I can manage to get one step closer and add the sign-in code for GEE, but the same error message pops up. I had rgee working two days ago, but now can't get past the first step!

**Comment by RussellGrayxd** [comment]
I am having the same issue. I have used rgee with no problem in the past and now I can't even get past the first steps of initialization. Can someone please respond to the issue?

**Comment by RussellGrayxd** [comment]
I managed to fix it... if you're passing the check but not the initialization, its a credential error and not a Python error, even though the error tracebacks are making it seem as if it is. 

Simple run:

# clean credentials
ee_clean_credentials()
# initialize earth engine
ee_Initialize()

Re-sign in with your rgee associated gmail once you initialize and it will work again

**Comment by leeyounguni** [comment]
please add proxy setting command of R before  initialization , 
Sys.setenv(http_proxy='http://127.0.0.1:1080')
Sys.setenv(https_proxy='http://127.0.0.1:1080')

**Comment by csaybar** [comment]
@leeyounguni should solve the problem

**Comment by kongdd** [comment]
I have the same issue. @leeyounguni's solution didn't solve my problem.
```R
r$> Sys.setenv(http_proxy = "http://127.0.0.1:1081")
    Sys.setenv(https_proxy = "http://127.0.0.1:1081")

r$> ee_Initialize()
── rgee 1.1.4 ─────────────────────────────────────────────────────────────────────────────── earthengine-api 0.1.317 ─ 
 ✔ user: not_defined
 ✔ Initializing Google Earth Engine:Error in py_call_impl(callable, dots$args, dots$keywords) : 
  TimeoutError: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。

r$> ee_clean_credentials()
Credentials in C:\Users\kong/.config/earthengine//ndef has been deleted.

r$> ee_Initialize()
── rgee 1.1.4 ─────────────────────────────────────────────────────────────────────────────── earthengine-api 0.1.317 ─ 
 ✔ user: not_defined
 ✔ Initializing Google Earth Engine:Fetching credentials using gcloud
Your browser has been opened to visit:

    https://accounts.google.com/o/oauth2/auth?response_type=code&client_id=517222506229-vsmmajv00ul0bs7p89v5m89qs8eb9359.apps.googleusercontent.com&redirect_uri=http%3A%2F%2Flocalhost%3A8085%2F&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fearthengine+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdevstorage.full_control+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Faccounts.reauth&state=x1xwY3EBu9QtlTq2zPcB7nP00LbTof&access_type=offline&code_challenge=0LCnMvE9pA2ua8wpkELFjTUMa1VlKCy1KQo4yxsqavk&code_challenge_method=S256


Credentials saved to file: [C:\Users\kong\AppData\Roaming\gcloud\application_default_credentials.json]

These credentials will be used by any library that requests Application Default Credentials (ADC).

Successfully saved authorization token.
Error in py_call_impl(callable, dots$args, dots$keywords) : 
  TimeoutError: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
```

**Comment by kongdd** [comment]
The final solution can be found at <https://github.com/r-spatial/rgee/issues/274#issuecomment-1186552176>
